chore(CI): Update main php testing versions and workflow templates
Signed-off-by: Joas Schilling <coding@schilljs.com>

diff --git a/.github/workflows/psalm-matrix.yml b/.github/workflows/psalm-matrix.yml
--- a/.github/workflows/psalm-matrix.yml
+++ b/.github/workflows/psalm-matrix.yml
@@ -3,57 +3,59 @@
 # https://github.com/nextcloud/.github
 # https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
 
-name: Lint
+name: Static analysis
 
 on:
   pull_request:
   push:
     branches:
-      - main
       - master
+      - main
       - stable*
 
-permissions:
-  contents: read
-
 concurrency:
-  group: lint-php-${{ github.head_ref || github.run_id }}
+  group: psalm-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true
 
 jobs:
-  php-lint:
+  static-analysis:
     runs-on: ubuntu-latest
     strategy:
+      # do not stop on another job's failure
+      fail-fast: false
       matrix:
-        php-versions: [ "8.0", "8.1", "8.2" ]
+        ocp-version: [ 'dev-master', 'dev-stable25' ]
 
-    name: php-lint
-
+    name: Nextcloud ${{ matrix.ocp-version }}
     steps:
       - name: Checkout
         uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
 
-      - name: Set up php ${{ matrix.php-versions }}
+      - name: Set up php
         uses: shivammathur/setup-php@1a18b2267f80291a81ca1d33e7c851fe09e7dfc4 # v2
         with:
-          php-version: ${{ matrix.php-versions }}
+          php-version: 8.0
           coverage: none
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Lint
-        run: composer run lint
+      - name: Install dependencies
+        run: composer i
+
+      - name: Install dependencies
+        run: composer require --dev nextcloud/ocp:${{ matrix.ocp-version }} --ignore-platform-reqs
+
+      - name: Run coding standards check
+        run: composer run psalm
 
   summary:
-    permissions:
-      contents: none
     runs-on: ubuntu-latest
-    needs: php-lint
+    needs: static-analysis
 
     if: always()
 
-    name: php-lint-summary
+    name: static-psalm-analysis-summary
 
     steps:
       - name: Summary status
-        run: if ${{ needs.php-lint.result != 'success' && needs.php-lint.result != 'skipped' }}; then exit 1; fi
+        run: if ${{ needs.static-analysis.result != 'success' }}; then exit 1; fi
